version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "delivery_db"
    ports:
      - "5432:5432"